name: Deploy to GitHub Pages

on:
  # 在推送到 main 分支時執行
  push:
    branches:
      - main

# 設定 workflow 的權限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # 建立與部署的工作
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 步驟 1: 下載您的程式碼
      - name: Checkout
        uses: actions/checkout@v4 # 更新到 v4

      # 步驟 2: 替換 Firebase 設定的預留位置
      - name: Replace Firebase Config Placeholders
        run: |
          sed -i 's|__API_KEY__|${{ secrets.API_KEY }}|g' index.html
          sed -i 's|__AUTH_DOMAIN__|${{ secrets.AUTH_DOMAIN }}|g' index.html
          sed -i 's|__PROJECT_ID__|${{ secrets.PROJECT_ID }}|g' index.html
          sed -i 's|__STORAGE_BUCKET__|${{ secrets.STORAGE_BUCKET }}|g' index.html
          sed -i 's|__MESSAGING_SENDER_ID__|${{ secrets.MESSAGING_SENDER_ID }}|g' index.html
          sed -i 's|__APP_ID__|${{ secrets.APP_ID }}|g' index.html
          sed -i 's|__MEASUREMENT_ID__|${{ secrets.MEASUREMENT_ID }}|g' index.html

      # 步驟 3: 設定 GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5 # 更新到 v5

      # 步驟 4: 上傳網站檔案成品
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 更新到 v3
        with:
          path: '.'

      # 步驟 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 更新到 v4
